---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: jekyll-posts
  label: News
  create: all
  templates:
  - post
- type: directory
  path: _projects
  label: Articles
  create: all
  match: "*"
  templates:
  - project
- type: directory
  path: _instructions
  label: Instructions
  create: all
  match: "**/*"
  templates:
  - landing-page
  - project
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - landing-page
  - default
- type: directory
  path: _people
  label: Teams
  create: all
  match: "*"
  templates:
  - person
- type: document
  path: _data/information.yml
  label: Contact Information
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
